FROM openjdk:8u181-jdk-stretch

MAINTAINER Numery Zaber "support@softwaredeveloper.com"

EXPOSE 8080

COPY maven/employee-service-mysql-0.0.1-SNAPSHOT.jar employee-service-mysql.jar 

CMD ["java","-jar","employee-service-mysql.jar"]